import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    passes: [
      {
        cacheKey: ["source.image", "mediaAssets[].transform"],
        id: "source-decode",
        inputs: ["source.image"],
        invalidatedBy: ["source.image", "mediaAssets[].transform"],
        kind: "decode",
        output: "source",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["source.image", "mediaAssets[].transform", "canvas.size", "selectedLayer.cellSize"],
        id: "webgl-cell-sampling",
        inputs: ["source-decode", "canvas.size", "selectedLayer.cellSize"],
        invalidatedBy: ["source.image", "mediaAssets[].transform", "canvas.size", "selectedLayer.cellSize"],
        kind: "pixel-transform",
        output: "intermediate",
        quality: "preview",
        runsOn: "gpu",
      },
      {
        cacheKey: ["selectedLayer.charset", "selectedLayer.cellSize"],
        id: "ascii-glyph-layout",
        inputs: ["webgl-cell-sampling", "selectedLayer.charset", "selectedLayer.cellSize"],
        invalidatedBy: ["selectedLayer.charset", "selectedLayer.cellSize"],
        kind: "text-layout",
        output: "intermediate",
        quality: "preview",
        runsOn: "main",
      },
      {
        cacheKey: [
          "selectedLayer.charset",
          "selectedLayer.cellSize",
          "selectedLayer.contrast",
          "selectedLayer.brightness",
          "selectedLayer.invert",
          "selectedLayer.colorMode",
          "selectedLayer.ink",
          "appearance.background",
          "export.includeBackground",
          "canvas.renderScale",
        ],
        id: "ascii-rasterize",
        inputs: [
          "ascii-glyph-layout",
          "selectedLayer.contrast",
          "selectedLayer.brightness",
          "selectedLayer.invert",
          "selectedLayer.colorMode",
          "selectedLayer.ink",
          "appearance.background",
          "export.includeBackground",
          "canvas.renderScale",
        ],
        invalidatedBy: [
          "selectedLayer.charset",
          "selectedLayer.cellSize",
          "selectedLayer.contrast",
          "selectedLayer.brightness",
          "selectedLayer.invert",
          "selectedLayer.colorMode",
          "selectedLayer.ink",
          "appearance.background",
          "export.includeBackground",
          "canvas.renderScale",
        ],
        kind: "rasterize",
        output: "preview",
        quality: "retina",
        runsOn: "main",
      },
      {
        id: "png-export",
        inputs: ["source-decode", "webgl-cell-sampling", "ascii-rasterize", "export.image.resolution"],
        invalidatedBy: ["export.image.format", "export.image.resolution"],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "export-only",
      },
    ],
    interactionInvalidation: [
      {
        interaction: "media-import",
        invalidates: ["source-decode", "webgl-cell-sampling", "ascii-glyph-layout", "ascii-rasterize"],
        targets: ["source.image"],
      },
      {
        interaction: "control-drag",
        invalidates: ["webgl-cell-sampling", "ascii-glyph-layout", "ascii-rasterize"],
        mustNotInvalidate: ["source-decode"],
        targets: ["selectedLayer.cellSize"],
      },
      {
        interaction: "control-drag",
        invalidates: ["ascii-rasterize"],
        mustNotInvalidate: ["source-decode", "webgl-cell-sampling"],
        targets: ["selectedLayer.contrast", "selectedLayer.brightness"],
      },
      {
        interaction: "control-change",
        invalidates: ["ascii-glyph-layout", "ascii-rasterize"],
        mustNotInvalidate: ["source-decode"],
        targets: ["selectedLayer.charset", "selectedLayer.invert", "selectedLayer.colorMode", "selectedLayer.ink", "appearance.background", "export.includeBackground"],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: ["source-decode", "webgl-cell-sampling", "ascii-glyph-layout", "ascii-rasterize"],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "viewport-drag",
        invalidates: [],
        mustNotInvalidate: ["source-decode", "webgl-cell-sampling", "ascii-glyph-layout", "ascii-rasterize"],
        targets: ["canvas.viewport"],
      },
      {
        interaction: "export",
        invalidates: ["png-export"],
        targets: ["export.image.format", "export.image.resolution"],
      },
    ],
  },
  rendererStrategy: "webgl",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "ASCII glyphs are intentionally rasterized into the output image so export dimensions and background alpha are exact.",
      "Very small cell sizes create dense text and can expose browser font rasterization differences.",
    ],
    intentionalRasterizationReason:
      "The product is an image effect export; glyph text is rasterized into PNG/JPG bytes at the selected Toolcraft output size.",
    layers: [
      {
        content: ["bitmap-media"],
        exportMode: "composited",
        id: "backgroundLayer",
        kind: "background",
        primitiveCount: "medium",
        renderer: "webgl",
        uiSelector: '[data-toolcraft-renderer-layer="ascii-product"]',
      },
      {
        content: ["text"],
        exportMode: "included",
        id: "productForegroundLayer",
        intentionalRasterizationReason:
          "The ASCII text effect is rasterized into a still image export, and browser tests verify native preview/output dimensions.",
        kind: "product-foreground",
        primitiveCount: "high",
        renderer: "canvas-2d",
        uiSelector: '[data-toolcraft-renderer-layer="ascii-product"]',
      },
      {
        content: ["composite"],
        exportMode: "included",
        id: "exportComposite",
        kind: "export-composite",
        primitiveCount: "medium",
        renderer: "canvas-2d",
      },
    ],
    measuredAlternativeEvidence: [
      {
        alternativeStrategy: "webgl",
        decision:
          "Keep source sampling on WebGL and glyph rasterization on Canvas 2D because WebGL cannot natively draw font glyphs without a separate atlas while Canvas text export preserves the product quality.",
        fixture: "3840x2160 media source, 1920x1080 canvas, 6px cell size, renderScale 2",
        measuredResult:
          "The implemented WebGL sampling pass is the selected GPU path; Canvas 2D is limited to text rasterization and export composition.",
        scenarioId: "ascii-preview-render",
      },
    ],
    performanceRisks: [
      "Cell size controls glyph count and is the highest-frequency workload path.",
      "8K export can produce a large text rasterization pass and is covered as an export workload.",
    ],
    previewExportDifferenceReason:
      "Preview uses the current visible canvas backing and render scale, while export uses createToolcraftPngExportCanvas to render the same ASCII effect at selected 2K/4K/8K output dimensions.",
    previewRenderer: "webgl",
    productRepresentation: "pixel",
    rendererStrategy: "webgl",
    rendererWorkload: "pixel-output",
    sourceRepresentation: "image-media",
    whyNotAlternativeStrategies: [
      "DOM text would preserve selectable characters but would not export the uploaded image effect as exact pixels through the standard PNG helper.",
      "Pure SVG would not provide efficient image sampling for dense ASCII conversion from arbitrary uploads.",
      "Pure Canvas 2D source sampling was rejected for the heavy media path; WebGL owns the cell sampling pass.",
    ],
  },
  rendererWorkload: "pixel-output",
  scenarios: [
    {
      automated: true,
      automatedTestName: "perf: Source image import stays responsive",
      browser: true,
      browserTestName: "browser perf: Source image import stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1500, maxLongTaskMs: 180 },
      controlLabel: "Image",
      expectedObservable:
        "Importing a source image updates media preview and ASCII output without blocking the app.",
      fixture: "3840x2160 source image import fixture",
      id: "ascii-media-import",
      interaction: "media-import",
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { width: 3840, height: 2160 },
          metric: "media-area",
          smoothTarget: { width: 3840, height: 2160 },
          smoothTargetRatio: 1,
          target: "source.image",
          userFacingRange: "fully-guaranteed",
        },
        reason: "A 4K-class upload is the heaviest realistic source material for this app.",
        value: { width: 3840, height: 2160 },
      },
      target: "source.image",
      values: {
        default: null,
        max: { width: 3840, height: 2160 },
        min: null,
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: Source image control coverage uses heavy media",
      browser: true,
      browserTestName: "browser perf: Source image control coverage uses heavy media",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 1500, maxLongTaskMs: 180 },
      controlLabel: "Image",
      expectedObservable:
        "Changing the source image control uses a 4K-class media fixture and updates ASCII output.",
      fixture: "3840x2160 source image control fixture",
      id: "ascii-source-control-change",
      interaction: "control-change",
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { width: 3840, height: 2160 },
          metric: "media-area",
          smoothTarget: { width: 3840, height: 2160 },
          smoothTargetRatio: 1,
          target: "source.image",
          userFacingRange: "fully-guaranteed",
        },
        reason: "A 4K-class upload is the heaviest realistic source material for this app.",
        value: { width: 3840, height: 2160 },
      },
      target: "source.image",
      values: {
        default: { width: 1920, height: 1080 },
        max: { width: 3840, height: 2160 },
        min: { width: 640, height: 360 },
      },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { renderScale: 2 },
          metric: "custom",
          smoothTarget: { renderScale: 2 },
          smoothTargetRatio: 1,
          target: "canvas.renderScale",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Source image import is measured with maximum preview render scale.",
        value: { renderScale: 2 },
      },
    },
    {
      automated: true,
      automatedTestName: "perf: ASCII preview render stays under budget",
      browser: true,
      browserTestName: "browser perf: ASCII preview render stays under budget",
      budget: { maxLongTaskMs: 180, maxPreviewMs: 1800 },
      expectedObservable:
        "Worst-case ASCII preview renders visible glyph output without freezing the app.",
      fixture: "3840x2160 source image, renderScale 2, 6px cell size",
      id: "ascii-preview-render",
      interaction: "preview-render",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { cellSize: 6, renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
          metric: "custom",
          smoothTarget: { cellSize: 6, renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
          smoothTargetRatio: 1,
          target: "ascii.preview",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "The heaviest preview combines a 4K-class media source, maximum render scale, and smallest exposed glyph cell size.",
        value: {
          cellSize: 6,
          renderScale: 2,
          sourceMedia: { width: 3840, height: 2160 },
        },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Glyph selector change stays responsive",
      browser: true,
      browserTestName: "browser perf: Glyph selector change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
      controlLabel: "Glyphs",
      expectedObservable: "Changing Glyphs updates ASCII text mapping without viewport jank.",
      fixture: "uploaded contrast image",
      id: "ascii-glyphs-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "fine",
          metric: "custom",
          smoothTarget: "fine",
          smoothTargetRatio: 1,
          target: "selectedLayer.charset",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Fine is the longest glyph ramp exposed by the app.",
        value: "fine",
      },
      target: "selectedLayer.charset",
      values: { default: "classic", max: "fine", min: "blocks" },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
          metric: "custom",
          smoothTarget: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
          smoothTargetRatio: 1,
          target: "ascii.sourceWorkload",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "The independent heavy baseline is a 4K-class uploaded source at the maximum preview render scale.",
        value: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
      },
    },
    {
      automated: true,
      automatedTestName: "perf: Cell size drag stays responsive at heavy source",
      browser: true,
      browserTestName: "browser perf: Cell size drag stays responsive at heavy source",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 1200, maxLongTaskMs: 180 },
      controlLabel: "Cell size",
      expectedObservable:
        "Dragging Cell size at a 4K-class source and renderScale 2 updates ASCII density without viewport jank.",
      fixture: "3840x2160 source image with renderScale 2",
      id: "ascii-cell-size-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "high-density",
        loadProfile: {
          hardLimit: 6,
          metric: "numeric-min",
          smoothTarget: 6,
          smoothTargetRatio: 1,
          target: "selectedLayer.cellSize",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Cell size 6px is the densest exposed ASCII grid.",
        value: 6,
      },
      target: "selectedLayer.cellSize",
      values: { default: 12, max: 32, min: 6 },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
          metric: "custom",
          smoothTarget: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
          smoothTargetRatio: 1,
          target: "ascii.sourceWorkload",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "The independent heavy baseline is a 4K-class uploaded source at the maximum preview render scale.",
        value: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
      },
    },
    {
      automated: true,
      automatedTestName: "perf: Contrast drag stays responsive at heavy source",
      browser: true,
      browserTestName: "browser perf: Contrast drag stays responsive at heavy source",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 1000, maxLongTaskMs: 180 },
      controlLabel: "Contrast",
      expectedObservable: "Dragging Contrast updates ASCII tone mapping without blocking input.",
      fixture: "3840x2160 source image with renderScale 2",
      id: "ascii-contrast-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 2.5,
          metric: "numeric-max",
          smoothTarget: 2.5,
          smoothTargetRatio: 1,
          target: "selectedLayer.contrast",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Maximum contrast is the heaviest useful tone remap value.",
        value: 2.5,
      },
      target: "selectedLayer.contrast",
      values: { default: 1.2, max: 2.5, min: 0.5 },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
          metric: "custom",
          smoothTarget: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
          smoothTargetRatio: 1,
          target: "ascii.sourceWorkload",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Contrast is measured over the active 4K-class source baseline.",
        value: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
      },
    },
    {
      automated: true,
      automatedTestName: "perf: Brightness drag stays responsive at heavy source",
      browser: true,
      browserTestName: "browser perf: Brightness drag stays responsive at heavy source",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 1000, maxLongTaskMs: 180 },
      controlLabel: "Brightness",
      expectedObservable: "Dragging Brightness updates ASCII tone mapping without blocking input.",
      fixture: "3840x2160 source image with renderScale 2",
      id: "ascii-brightness-drag",
      interaction: "control-drag",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: 50,
          metric: "numeric-max",
          smoothTarget: 50,
          smoothTargetRatio: 1,
          target: "selectedLayer.brightness",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Maximum brightness shift is the heaviest exposed brightness value.",
        value: 50,
      },
      target: "selectedLayer.brightness",
      values: { default: 0, max: 50, min: -50 },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
          metric: "custom",
          smoothTarget: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
          smoothTargetRatio: 1,
          target: "ascii.sourceWorkload",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Brightness is measured over the active 4K-class source baseline.",
        value: { renderScale: 2, sourceMedia: { width: 3840, height: 2160 } },
      },
    },
    {
      automated: true,
      automatedTestName: "perf: Invert toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: Invert toggle stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 700 },
      controlLabel: "Invert",
      expectedObservable: "Invert updates glyph tone mapping without viewport jank.",
      fixture: "uploaded contrast image",
      id: "ascii-invert-change",
      interaction: "control-change",
      target: "selectedLayer.invert",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Object arrange actions stay responsive",
      browser: true,
      browserTestName: "browser perf: Object arrange actions stay responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 900 },
      controlLabel: "Duplicate",
      expectedObservable:
        "Duplicate and bring-to-front/send-to-back update the scene and layer order without viewport jank.",
      fixture: "two uploaded image objects",
      id: "ascii-arrange-change",
      interaction: "control-change",
      target: "actions.object",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Color mode select stays responsive",
      browser: true,
      browserTestName: "browser perf: Color mode select stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 700 },
      controlLabel: "Color",
      expectedObservable: "Color mode switches mono/source glyph coloring without viewport jank.",
      fixture: "uploaded colored image",
      id: "ascii-color-mode-change",
      interaction: "control-change",
      target: "selectedLayer.colorMode",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Ink color change stays responsive",
      browser: true,
      browserTestName: "browser perf: Ink color change stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 700 },
      controlLabel: "Ink",
      expectedObservable: "Ink color changes mono glyph fill without viewport jank.",
      fixture: "uploaded contrast image",
      id: "ascii-ink-change",
      interaction: "control-change",
      target: "selectedLayer.ink",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Include background toggle stays responsive",
      browser: true,
      browserTestName: "browser perf: Include background toggle stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 700 },
      controlLabel: "Include",
      expectedObservable: "Include toggles preview background compositing without viewport jank.",
      fixture: "uploaded contrast image",
      id: "ascii-include-background-change",
      interaction: "control-change",
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Background color change stays responsive",
      browser: true,
      browserTestName: "browser perf: Background color change stays responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 700 },
      controlLabel: "Include",
      expectedObservable: "Background color changes preview fill without viewport jank.",
      fixture: "uploaded contrast image",
      id: "ascii-background-change",
      interaction: "control-change",
      target: "appearance.background",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Image format select stays responsive",
      browser: true,
      browserTestName: "browser perf: Image format select stays responsive",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 700 },
      controlLabel: "Format",
      expectedObservable: "Format selection updates export state without viewport jank.",
      fixture: "uploaded contrast image",
      id: "ascii-format-change",
      interaction: "control-change",
      target: "export.image.format",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: Image resolution select uses export workload values",
      browser: true,
      browserTestName: "browser perf: Image resolution select uses export workload values",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 700 },
      controlLabel: "Resolution",
      expectedObservable:
        "Resolution selection changes export workload state through the real select control.",
      fixture: "uploaded contrast image",
      id: "ascii-resolution-change",
      interaction: "control-change",
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "8k",
          metric: "custom",
          smoothTarget: "8k",
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K is the largest still export tier exposed by the app.",
        value: "8k",
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
      workloadFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { sourceMedia: { width: 3840, height: 2160 } },
          metric: "custom",
          smoothTarget: { sourceMedia: { width: 3840, height: 2160 } },
          smoothTargetRatio: 1,
          target: "source.image",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Resolution selection is measured with a 4K-class uploaded source.",
        value: { sourceMedia: { width: 3840, height: 2160 } },
      },
    },
    {
      automated: true,
      automatedTestName: "perf: ASCII export completes at selected resolution",
      browser: true,
      browserTestName: "browser perf: ASCII export completes at selected resolution",
      budget: { maxExportMs: 8000, maxLongTaskMs: 220 },
      expectedObservable:
        "Export PNG produces selected-resolution bytes from the ASCII output without corrupting the canvas preview.",
      fixture: "uploaded image exported at 4K",
      id: "ascii-export",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { resolution: "4k", sourceMedia: { width: 3840, height: 2160 } },
          metric: "custom",
          smoothTarget: { resolution: "4k", sourceMedia: { width: 3840, height: 2160 } },
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "4K export is the default final-delivery resolution and uses a 4K-class source fixture.",
        value: { resolution: "4k", sourceMedia: { width: 3840, height: 2160 } },
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "2k" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "perf: ASCII viewport zoom stays stable",
      browser: true,
      browserTestName: "browser perf: ASCII viewport zoom stays stable",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1200, maxLongTaskMs: 180 },
      expectedObservable:
        "Toolbar zoom changes the Toolcraft viewport without recomputing source decode or causing output jumps.",
      fixture: "dense ASCII output at renderScale 2",
      id: "ascii-viewport-zoom",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { cellSize: 6, renderScale: 2 },
          metric: "custom",
          smoothTarget: { cellSize: 6, renderScale: 2 },
          smoothTargetRatio: 1,
          target: "ascii.viewportZoom",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Zoom stress uses dense ASCII output with maximum render scale so viewport work is measured over the heavy renderer layer.",
        value: { cellSize: 6, renderScale: 2 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: ASCII viewport remains stable",
      browser: true,
      browserTestName: "browser perf: ASCII viewport remains stable",
      budget: { maxFrameGapMs: 90, maxInteractionMs: 900 },
      expectedObservable:
        "Changing lightweight controls does not shift canvas viewport offset or zoom.",
      fixture: "uploaded contrast image",
      id: "ascii-viewport-stability",
      interaction: "viewport-stability",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: object composite scene stays under budget",
      browser: true,
      browserTestName: "browser perf: object composite scene stays under budget",
      budget: { maxLongTaskMs: 220, maxPreviewMs: 2000 },
      expectedObservable:
        "Compositing many cached image objects into the canvas stays under budget because only changed objects re-rasterize.",
      fixture: "5 image objects on one artboard at renderScale 2",
      id: "ascii-object-composite",
      interaction: "preview-render",
      stress: true,
      stressFixture: {
        kind: "custom",
        loadProfile: {
          hardLimit: { objectCount: 5, renderScale: 2 },
          metric: "custom",
          smoothTarget: { objectCount: 5, renderScale: 2 },
          smoothTargetRatio: 1,
          target: "ascii.objectComposite",
          userFacingRange: "fully-guaranteed",
        },
        reason:
          "Five cached image objects is the maximum supported multi-object composite; only re-rasterizing changed objects keeps paints cheap.",
        value: { objectCount: 5, renderScale: 2 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "perf: layer interactions keep viewport stable",
      browser: true,
      browserTestName: "browser perf: layer interactions keep viewport stable",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1200, maxLongTaskMs: 180 },
      expectedObservable:
        "Zoom/radar, layer selection, visibility toggling, reorder or grouping, and selected-layer output edits keep the canvas viewport stable without jank.",
      fixture: "several objects with the Layers panel open",
      id: "ascii-layers-interactions",
      interaction: "viewport-stability",
      target: "layers.interactions",
      workload: false,
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "source.image",
    "selectedLayer.charset",
    "selectedLayer.cellSize",
    "selectedLayer.contrast",
    "selectedLayer.brightness",
    "export.image.resolution",
  ],
});
